### ISSUE TITLE
"!->" doesn't work

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eolang.sty#12]
If we write this:
```
\begin{phiquation*}
@ !-> x.lt
\end{phiquation*}
```
we get this arrow:
![image](https://user-images.githubusercontent.com/95661085/198080676-6d779e21-a25c-42e6-b4a2-38abac1047f1.png)

It is not so differs from the default `\mapsto`:
![image](https://user-images.githubusercontent.com/95661085/198080758-d271c1c3-c8ad-4f83-8bd4-4648cd35971a.png)

@yegor FYI

**Comment by MikhailLipanin** [comment]
Or does the type of the arrow depend on the font size in the document?

**Comment by yegor256** [comment]
@MikhailLipanin please, post the entire code, to let me repeat this bug locally

**Comment by yegor256** [comment]
@MikhailLipanin it doesn't work with `acmart`. It's a bug. Let me try to fix it.

**Comment by yegor256** [comment]
@MikhailLipanin it's fixed in 1412a16, I believe. Try to use the latest version of `eolang.sty` file.
